### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by bpolaszek** [clue/reactphp-eventsource#16]
Hello there! I didn't figure out how I could set an `Authorization` header, when connecting to a restricted event source.

Is it something possible?

Thank you!
Ben

**Comment by clue** [comment]
@bpolaszek Thanks for this excellent question!

This project supports HTTP basic authentication when you include your login credentials in the `EventSource` URL like this:

```php
$stream = new Clue\React\EventSource\EventSource('https://user:pass@example.com/', $loop);
```

Additionally, there are plans to support setting arbitrary request headers as per #10. Join in the conversation if you feel this helps with your use case :+1: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
